In [2]:
# Write a Python program to print the NumPy
# version in your system
import numpy as np 
print(np.__version__)

1.21.5


In [11]:
# Write a Python program to reverse an array
# (first element becomes last)
def my_arr_rev(arr):
    lst=list(arr)
    lst.reverse()
    arr1=np.array(lst)
    return arr1
my_arr_rev(np.array([1,2,3,4,5]))   

array([5, 4, 3, 2, 1])

In [18]:
# Write a Python program to convert a list and
# tuple into arrays.
def list_to_arr(lst):
    arr1=np.array(lst)
    return (arr1 ,type(arr1))
print(list_to_arr([1,2,3,4,5]))
def tuple_to_arr(tuple1):
    arr1=np.array(tuple1)
    return (arr1 ,type(arr1))
print(tuple_to_arr((1,2,3,4,5)))

(array([1, 2, 3, 4, 5]), <class 'numpy.ndarray'>)
(array([1, 2, 3, 4, 5]), <class 'numpy.ndarray'>)


In [20]:
# Write a Python program to find common values
# between two arrays.
def common_values(arr1,arr2):
    lst1=list(arr1)
    lst2=list(arr2)
    lst=[]
    for i in lst1:
        if i in lst2:
            lst.append(i)
    lst
    arr3=np.array(lst)
    return arr3
common_values(np.array([1,2,3,4,5,89,76]),np.array([2,5,89,65,67]))

array([ 2,  5, 89])

In [22]:
a=np.array([1,2,3,4,5,89,76])
b=np.array([1,2,89,65])
np.intersect1d(a,b)


array([ 1,  2, 89])

In [25]:
a=np.array([1,2,3,4,5,89,76,43]).reshape(2,4)
b=np.array([1,2,89,65,43,4]).reshape(2,3)
np.intersect1d(a,b)


array([ 1,  2,  4, 43, 89])

In [37]:
# Write a Python program compare two arrays
# using numpy.
a=np.array([1,2,3,4,-5,-6,8])
b=np.array([1,-2,8,4,5,-6,-8])
print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

a > b
[False  True False False False False  True]
a >= b
[ True  True False  True False  True  True]
a < b
[False False  True False  True False False]
a <= b
[ True False  True  True  True  True False]


In [49]:
# Write a Python program to change the
# dimension of an array


a=np.arange(1,10)
print(a)
b=a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# Write a Python program (using numpy) to sum
# of all the multiples of 3 or 5 below 100

a=np.arange(1,101)
k=0
for i in range(len(a)):
    if a[i]%3==0 or a[i]%5==0:
        k=k+a[i]
print(k)
        

2418


In [54]:
# Write a Python program to convert a NumPy
# array into Python list structure.
def arr_to_lst(arr):
    lst=list(arr)
    print(lst)
arr_to_lst(np.array(np.arange(1,10)))


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [61]:
#  Write a Python program to how to add an extra
# column to a numpy array.
a=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
b=np.array([1,1])
def inserting(a,b):
    c =np.insert(a,b,1,axis=1)
    return c
    
inserting(a,b)

array([[1, 1, 1, 2, 3, 4],
       [5, 1, 1, 6, 7, 8]])

In [15]:
# Write a Python program to check whether the
# numpy array is empty or not
import numpy as np
def empty_(my_arr):
    if my_arr.size==0:
        
        print('empty')
    else:
        print('non-empty')
    
empty_(np.array([]))

empty


In [16]:
empty_(np.array([1,2,3,4]))

non-empty


In [19]:
# Write a Python program to normalize a 3x3 
# random matrix.
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
print(x.min())
print(x.max())
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.92462346 0.43669637 0.12440767]
 [0.56524362 0.15032591 0.19056167]
 [0.03536978 0.161614   0.03855175]]
0.03536977637366456
0.9246234602843225
After normalization:
[[1.         0.45130721 0.10012654]
 [0.59586354 0.12927259 0.17451925]
 [0.         0.14196649 0.00357826]]


In [ ]:
# How to ignore all numpy warnings (not 
# recommended)?

In [42]:
# How to swap two rows of an array?
np.random.seed(101)
arr=np.arange(1,9).reshape(4,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
arr[[0,1]]=arr[[1,0]]
arr

array([[3, 4],
       [1, 2],
       [5, 6],
       [7, 8]])

In [46]:
# arr[:,[1,0]]=arr[:,[0,1]]
# arr

array([[4, 3],
       [2, 1],
       [6, 5],
       [8, 7]])

In [ ]:
# Compute bootstrapped 95% confidence 
# intervals for the mean of a 1D array X (i.e., 
# resample the elements of an array with 
# replacement N times, compute the mean of 
# each sample, and then compute percentiles 
# over the means)



##### couldnt understood the problem

In [64]:
#  Python program to create a random vector of 
# size 10 and sort it.

arr=np.array([1,23,4,578,78,98,76,43,88,90]).reshape(1,10)
print(arr)
arr1=np.sort(arr)
print(arr1)


[[  1  23   4 578  78  98  76  43  88  90]]
[[  1   4  23  43  76  78  88  90  98 578]]


In [65]:
#  Write a Python program to check two random 
# arrays are equal or not.
arr=np.array([1,23,4,578,78,98,76,43,88,90]).reshape(2,5)
arr2=np.array([1,23,4,578,78,98,76,43,88,90]).reshape(2,5)
print(arr==arr2)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [70]:
# Write a Python program to add, subtract, 
# multiply, divide arguments element-wise.
arr=np.random.randint(1,10,12).reshape(4,3)
arr1=np.random.randint(1,10,12).reshape(4,3)
arr2=arr+arr1
arr3=arr-arr1
arr4=arr*arr1
arr5=arr/arr1
print(arr,arr1,arr2,arr3,arr4,arr5,sep='\n')



[[5 4 2]
 [5 5 5]
 [3 4 2]
 [8 5 1]]
[[7 8 5]
 [1 8 3]
 [8 8 7]
 [6 3 9]]
[[12 12  7]
 [ 6 13  8]
 [11 12  9]
 [14  8 10]]
[[-2 -4 -3]
 [ 4 -3  2]
 [-5 -4 -5]
 [ 2  2 -8]]
[[35 32 10]
 [ 5 40 15]
 [24 32 14]
 [48 15  9]]
[[0.71428571 0.5        0.4       ]
 [5.         0.625      1.66666667]
 [0.375      0.5        0.28571429]
 [1.33333333 1.66666667 0.11111111]]


In [71]:
#  Write a Python program to get the dates of 
# yesterday, today and tomorrow
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-09-14
Today:  2022-09-15
Tomorrow:  2022-09-16
